version: "3"

services:
  web:
    container_name: webapp
    build: ./web
    command: npm start
    ports:
      - "8080:3000"
    environment:
      - PORT=3000
      - API_HOST=http://api:3000
    networks:
      - nodeapp
    restart: always

  api:
    container_name: apiapp 
    build: ./api
    depends_on:
      - db
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB=postgres://postgres:h4ck3r1918@db:5432/postgres
    networks:
      - nodeapp
    restart: always

  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=h4ck3r1918
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
       - ./postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - nodeapp
    restart: always

networks:
  nodeapp:
    driver: bridge

